const veeps = [
  { name: "John Adams", termStart: 1789, termEnd: 1797, president: "George Washington" },
  { name: "Thomas Jefferson", termStart: 1797, termEnd: 1801, president: "John Adams" },
  { name: "Aaron Burr", termStart: 1801, termEnd: 1805, president: "Thomas Jefferson" },
  { name: "George Clinton", termStart: 1805, termEnd: 1812, president: "Thomas Jefferson, James Madison" },
  { name: "Elbridge Gerry", termStart: 1813, termEnd: 1814, president: "James Madison" },
  { name: "Daniel D. Tompkins", termStart: 1817, termEnd: 1825, president: "James Monroe" },
  { name: "John C. Calhoun", termStart: 1825, termEnd: 1832, president: "John Quincy Adams, Andrew Jackson" },
  { name: "Martin Van Buren", termStart: 1833, termEnd: 1837, president: "Andrew Jackson" },
  { name: "Richard Mentor Johnson", termStart: 1837, termEnd: 1841, president: "Martin Van Buren" },
  { name: "John Tyler", termStart: 1841, termEnd: 1841, president: "William Henry Harrison" },
  { name: "George M. Dallas", termStart: 1845, termEnd: 1849, president: "James K. Polk" },
  { name: "Millard Fillmore", termStart: 1849, termEnd: 1850, president: "Zachary Taylor" },
  { name: "William R. King", termStart: 1853, termEnd: 1853, president: "Franklin Pierce" },
  { name: "John C. Breckinridge", termStart: 1857, termEnd: 1861, president: "James Buchanan" },
  { name: "Hannibal Hamlin", termStart: 1861, termEnd: 1865, president: "Abraham Lincoln" },
  { name: "Andrew Johnson", termStart: 1865, termEnd: 1865, president: "Abraham Lincoln" },
  { name: "Schuyler Colfax", termStart: 1869, termEnd: 1873, president: "Ulysses S. Grant" },
  { name: "Henry Wilson", termStart: 1873, termEnd: 1875, president: "Ulysses S. Grant" },
  { name: "William A. Wheeler", termStart: 1877, termEnd: 1881, president: "Rutherford B. Hayes" },
  { name: "Chester A. Arthur", termStart: 1881, termEnd: 1881, president: "James Garfield" },
  { name: "Thomas A. Hendricks", termStart: 1885, termEnd: 1885, president: "Grover Cleveland" },
  { name: "Levi P. Morton", termStart: 1889, termEnd: 1893, president: "Benjamin Harrison" },
  { name: "Adlai Stevenson I", termStart: 1893, termEnd: 1897, president: "Grover Cleveland" },
  { name: "Garret Hobart", termStart: 1897, termEnd: 1899, president: "William McKinley" },
  { name: "Theodore Roosevelt", termStart: 1901, termEnd: 1901, president: "William McKinley" },
  { name: "Charles W. Fairbanks", termStart: 1905, termEnd: 1909, president: "Theodore Roosevelt" },
  { name: "James S. Sherman", termStart: 1909, termEnd: 1912, president: "William Howard Taft" },
  { name: "Thomas R. Marshall", termStart: 1913, termEnd: 1921, president: "Woodrow Wilson" },
  { name: "Calvin Coolidge", termStart: 1921, termEnd: 1923, president: "Warren G. Harding" },
  { name: "Charles G. Dawes", termStart: 1925, termEnd: 1929, president: "Calvin Coolidge" },
  { name: "Charles Curtis", termStart: 1929, termEnd: 1933, president: "Herbert Hoover" },
  { name: "John Nance Garner", termStart: 1933, termEnd: 1941, president: "Franklin D. Roosevelt" },
  { name: "Henry A. Wallace", termStart: 1941, termEnd: 1945, president: "Franklin D. Roosevelt" },
  { name: "Harry S. Truman", termStart: 1945, termEnd: 1945, president: "Franklin D. Roosevelt" },
  { name: "Alben W. Barkley", termStart: 1949, termEnd: 1953, president: "Harry S. Truman" },
  { name: "Richard Nixon", termStart: 1953, termEnd: 1961, president: "Dwight D. Eisenhower" },
  { name: "Lyndon B. Johnson", termStart: 1961, termEnd: 1963, president: "John F. Kennedy" },
  { name: "Hubert Humphrey", termStart: 1965, termEnd: 1969, president: "Lyndon B. Johnson" },
  { name: "Spiro Agnew", termStart: 1969, termEnd: 1973, president: "Richard Nixon" },
  { name: "Gerald Ford", termStart: 1973, termEnd: 1974, president: "Richard Nixon" },
  { name: "Nelson Rockefeller", termStart: 1974, termEnd: 1977, president: "Gerald Ford" },
  { name: "Walter Mondale", termStart: 1977, termEnd: 1981, president: "Jimmy Carter" },
  { name: "George H. W. Bush", termStart: 1981, termEnd: 1989, president: "Ronald Reagan" },
  { name: "Dan Quayle", termStart: 1989, termEnd: 1993, president: "George H. W. Bush" },
  { name: "Al Gore", termStart: 1993, termEnd: 2001, president: "Bill Clinton" },
  { name: "Dick Cheney", termStart: 2001, termEnd: 2009, president: "George W. Bush" },
  { name: "Joe Biden", termStart: 2009, termEnd: 2017, president: "Barack Obama" },
  { name: "Mike Pence", termStart: 2017, termEnd: 2021, president: "Donald Trump" },
  { name: "Kamala Harris", termStart: 2021, termEnd: 2025, president: "Joe Biden" },
  { name: "JD Vance", termStart: 2025, termEnd: null, president: "Donald Trump" },
];

module.exports = veeps;
